# Generated by Django 3.1.6 on 2021-02-14 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Responsible',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsible', models.CharField(default='', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('note', models.TextField()),
                ('deadline', models.DateField()),
                ('status', models.CharField(choices=[('TODO', 'To do'), ('DOING', 'Doing'), ('DONE', 'Done')], max_length=50)),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.responsible')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.tag')),
            ],
        ),
    ]
